sudo: required
services:
  - docker
language: node_js
node_js:
  - "node"
install:
  - npm install
cache:
  directories:
  - "node_modules"
git:
  depth: false
script:
  - npm run lint
  - npm run build
  - npm run clone-repo
  - npm run test
deploy:
  - provider: script
    script: MODE=staging bash deploy_heroku.sh
    on:
      tags: false
  - provider: script
    script: MODE=production bash deploy_heroku.sh
    on:
      tags: true
