sudo: required
services:
  - docker
language: node_js
node_js:
  - "node"
cache:
  directories:
  - "node_modules"
git:
  depth: false
install:
  - npm install
addons:
    sauce_connect:
      username: bakoushin
      access_key: $SAUCELABS_AUTH      
script:
  - npm run lint
  - npm run build
  - npm run clone-repo
  - npm run test
  - npm start &
  - npm run hermione
deploy:
  - provider: heroku
    api_key: $HEROKU_AUTH
    app: shri-node-staging
    on:
      tags: false
  - provider: heroku
    api_key: $HEROKU_AUTH
    app: shri-node-production
    on:
      tags: true
